search_paths = []

[[search_dirs]]
path = '/Users/dwclake/work'
depth = 10

[[search_dirs]]
path = '/Users/dwclake/fpga'
depth = 10

[[search_dirs]]
path = '/Users/dwclake/embedded'
depth = 10

[[search_dirs]]
path = '/Users/dwclake/learning'
depth = 10

[[search_dirs]]
path = '/Users/dwclake/personal'
depth = 10
