import = ["/home/dwclake/.config/alacritty/themes/rose-pine/dist/rose-pine-moon.toml"]
#import = ["/home/dwclake/.config/alacritty/themes/nord/nord.toml"]

[font]
size = 12
#size = 11

[font.bold]
family = "IntOneMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IntOneMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IntOneMono Nerd Font Mono"
style = "Medium"

[font.normal]
family = "IntOneMono Nerd Font Mono" 
style = "Regular"

[font.offset]
#y = -4
y = -2

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 1

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true
