import = ["/home/dwclake/.config/alacritty/themes/rose-pine/dist/rose-pine-moon.toml"]

[font]
size = 12

[font.bold]
family = "IntelOneMono Nerd Font Mono"

[font.bold_italic]
family = "IntelOneMono Nerd Font Mono"

[font.italic]
family = "IntelOneMono Nerd Font Mono"

[font.normal]
family = "IntelOneMono Nerd Font Mono" 

[font.offset]
y = -2

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.70

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true
