import = ["/home/dwclake/.config/alacritty/themes/rose-pine/dist/rose-pine-moon.toml"]

[font]
size = 12

[font.bold]
family = "IntelOneMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IntelOneMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IntelOneMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IntelOneMono Nerd Font Mono" 
style = "Medium"

[font.offset]
y = -2

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.6

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true
