search_paths = []

[[search_dirs]]
path = '/home/dwclake/work'
depth = 10

[[search_dirs]]
path = '/home/dwclake/fpga'
depth = 10

[[search_dirs]]
path = '/home/dwclake/learning'
depth = 10

[[search_dirs]]
path = '/home/dwclake/personal'
depth = 10
