import = ["~/.config/alacritty/themes/rose-pine/dist/rose-pine-moon.toml"]

[font]
size = 16

[font.bold]
family = "IntOneMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IntOneMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IntOneMono Nerd Font Mono"
style = "Medium"

[font.normal]
family = "IntOneMono Nerd Font Mono" 
#style = "Medium"

[font.offset]
x = 1
y = 1

[window]
decorations = "Buttonless"

[window.dimensions]
columns = 300
lines = 250

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true
