name = "worktree: sight"

[[panes]]
commands = [
    "git worktree add -b {{branch_name}} /Users/dwclake/.warp/worktrees/eyeDHD/{{branch_name}} {{base_branch}}",
    "cd /Users/dwclake/.warp/worktrees/eyeDHD/{{branch_name}}",
]
directory = "/Users/dwclake/personal/eyeDHD"
id = "main"
type = "terminal"

[params.base_branch]
type = "branch"
description = "Base branch to branch from"

[params.branch_name]
type = "text"
description = "New branch name"
default = "feature"